name: End-to-End ML Pipeline (Thyroid)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib mlflow==2.19.0

      - name: Run Preprocessing
        run: |
          # Generate the data in the root
          python preprocessing/automate_Azzar-Budiyanto.py
          # Copy the generated data into the MLProject folder so it's accessible locally
          mkdir -p MLProject/preprocessing
          cp -r preprocessing/thyroid_preprocessing MLProject/preprocessing/

      - name: Run MLflow Project
        run: |
          export MLFLOW_ALLOW_FILE_STORE=true
          # Now preprocessing/thyroid_preprocessing exists INSIDE MLProject
          mlflow run MLProject --env-manager=local 
